# Laden der notwendigen Bibliotheken
library(tidyverse)

# 1. Erstellen einer Datenstruktur für CLC-Codes und deren Namen
clc_data <- tibble(
  CLC_Code = c(111, 112, 121, 122, 123, 124, 131, 132, 133, 141, 142, 
               211, 221, 222, 231, 242, 243, 311, 312, 313, 321, 
               322, 324, 331, 332, 333, 334, 335, 411, 412, 421, 
               423, 511, 512, 521, 522, 523),
  CLC_Klassenname_Englisch = c("Continuous urban fabric", 
                               "Discontinuous urban fabric", 
                               "Industrial or commercial units and public facilities", 
                               "Road and rail networks and associated land", 
                               "Port areas", 
                               "Airports", 
                               "Mineral extraction sites", 
                               "Dump sites", 
                               "Construction sites", 
                               "Green urban areas", 
                               "Sport and leisure facilities", 
                               "Non-irrigated arable land", 
                               "Vineyards", 
                               "Fruit tree and berry plantations", 
                               "Pastures, meadows and other permanent grasslands under agricultural use", 
                               "Complex cultivation patterns", 
                               "Land principally occupied by agriculture, with significant areas of natural vegetation", 
                               "Broad-leaved forest", 
                               "Coniferous forest", 
                               "Mixed forest", 
                               "Natural grassland", 
                               "Moors and heathland", 
                               "Transitional woodland/shrub", 
                               "Beaches, dunes and sand plains", 
                               "Bare rock", 
                               "Sparsely vegetated areas", 
                               "Burnt areas", 
                               "Glaciers and perpetual snow", 
                               "Inland marshes", 
                               "Peatbogs", 
                               "Coastal salt marshes", 
                               "Intertidal flats", 
                               "Water courses", 
                               "Water bodies", 
                               "Coastal lagoons", 
                               "Estuaries", 
                               "Sea and ocean"),
  CLC_Klassenname_Deutsch = c("Durchgängig städtische Prägung", 
                              "Nicht durchgängig städtische Prägung", 
                              "Industrie und Gewerbeflächen, öffentliche Einrichtungen", 
                              "Straßen-, Eisenbahnnetze und funktionell zugeordnete Flächen", 
                              "Hafengebiete", 
                              "Flughäfen", 
                              "Abbauflächen", 
                              "Deponien und Abraumhalden", 
                              "Baustellen", 
                              "Städtische Grünflächen", 
                              "Sport- und Freizeitanlagen", 
                              "Nicht bewässertes Ackerland", 
                              "Weinbauflächen", 
                              "Obst- und Beerenobstbestände", 
                              "Wiesen und Weiden", 
                              "Komplexe Parzellenstruktur", 
                              "Landwirtschaftlich genutztes Land mit Flächen natürlicher Bodenbedeckung von signifikanter Größe", 
                              "Laubwälder", 
                              "Nadelwälder", 
                              "Mischwälder", 
                              "Natürliches Grünland", 
                              "Heiden und Moorheiden", 
                              "Wald-Strauch-Übergangsstadien", 
                              "Strände, Dünen und Sandflächen", 
                              "Felsen ohne Vegetation", 
                              "Flächen mit spärlicher Vegetation", 
                              "Brandflächen", 
                              "Gletscher und Dauerschneegebiete", 
                              "Sümpfe", 
                              "Torfmoore", 
                              "Salzwiesen", 
                              "In der Gezeitenzone liegende Flächen", 
                              "Gewässerläufe", 
                              "Wasserflächen", 
                              "Lagunen", 
                              "Mündungsgebiete", 
                              "Meere und Ozeane")
)

print(clc_data)

# 2. Exportieren der Tabelle als CSV-Datei
write.csv(clc_data, "C:/Users/agnes/Documents/EAGLE/Innovation_Lab/Daten/COPERNICUS_CORINE_V20_100m/CLC_Klassen_Namen.csv", row.names = FALSE)

